### ISSUE TITLE
L matrix: How many columns?

### ISSUE THREAD

**Issue by jpuntomarcos** [binzhulab/SATS#2]
Hi,

Thank you very much for developing SATS, it can be very useful.

Regarding the L matrix, documentation says that size is 96 x P, where P is number of patients (or tumors).

However, the `L_matrix_generation()` function returns a 96 x number of gene panels, as we can see here:
```
> L_matrix_generation(Panel_2, Types = "signeR")
        GRCC-CP1 UHN-48-V1
C>A:ACA 0.000883  0.001487
C>A:ACC 0.000656  0.001120
C>A:ACG 0.000278  0.000426
```

If I want to analyze 100 tumors, my L matrix should contain 100 columns, right? Therefore, Should I perform more steps after `L_matrix_generation()` to get the **final** L matrix containing 96 x 100 columns?

Thanks in advance,
J.

**Comment by binzhulab** [comment]
Thank you for bringing this to our attention. 
As you correctly pointed out, the `L_matrix_generation()` function you showed does not produce the intended $\mathbf{L}$ matrix. It generates a panel context matrix corresponding to SEQ_ASSAY_ID rather than Patient_ID. Therefore, an additional step is required to obtain the final $\mathbf{L}$ matrix.

To address this, we have modified the original R script, and the updated version (L_matrix_Generation_V2.R) is available in the [Generating_L folder](https://github.com/binzhulab/SATS/tree/main/Generating_L). Detailed examples can also be found in Section 2 of the README. In summary, the reference panel context is first constructed using the `Panel_Context_generation()` function. The $\mathbf{L}$ matrix is subsequently generated from the reference panel context by matching SEQ_ASSAY_ID with Patient_ID using the (updated) `L_matrix_generation()` function. The Patient_info.txt in the [Generating_L folder](https://github.com/binzhulab/SATS/tree/main/Generating_L) contains patient IDs associated with SEQ_ASSAY_ID, which serves as an input to the (updated) `L_matrix_generation()` along with panel context matrix.

Hope this helps! Please let us know if you need any further information.
Thanks.

**Comment by jpuntomarcos** [comment]
Thanks for addressing this issue. The new function works and I generated the L matrix succesfully :)
